---
title: "Overview of EoI Reviews by TRC"
output:
  html_document:
    df_print: paged
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
---
<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup, include=FALSE}
library(ggplot2)
library(crosstalk)
library(reactable)
library(plotly)
library(plyr)
library(flexdashboard)

# Make some noisily increasing data


```

-----------------------------------------------------------------------
### Summary Data of all reviews, aggregated by EoI
##### Use the controls on the left to subset the summary table and plot that follows.

```{r echo = FALSE}

summaryStats <- read.csv("summaryStats.csv")
data <- SharedData$new(summaryStats)

bscols(
  widths = c(3, 9),
  list(
    filter_checkbox("geography", "Geography", data, ~Geography),
    filter_slider("average", "Average", data, ~Average, width = "100%"),
    filter_select("EoI", "EoI Number", data, ~EoI)
  ),
  reactable(data, 
            columns = list(
    EoI = colDef(minWidth = 75),
    Geography = colDef(minWidth = 115),
    Reviews = colDef(minWidth = 75),
    Average = colDef(minWidth = 75),
    Total = colDef(minWidth = 75),
    Min = colDef(minWidth = 75),
    Max = colDef(minWidth = 75),
    Range = colDef(minWidth = 75),
    Percentile = colDef(minWidth = 90),
    Rank = colDef(minWidth = 75)),
            minRows = 10,
            highlight = TRUE,
            striped = TRUE)

)
```

### Performance of EoIs - Percentile by Average Score

```{r echo = FALSE}
p <- ggplot(data, aes(x=Average, y=Percentile, color = Geography), group = Geography) +
            geom_point(shape=1)      # Use hollow circles



bscols(
  widths = c(8),
ggplotly(p)
)
```




***
# [Overview of Individual EoIs]{.ul}{.ul}


```{r echo = FALSE}

fullData <- readxl::read_xlsx("fulldata.xlsx")
full_Data <- SharedData$new(fullData[c(1,4:7)])

bscols(
  widths = c(3, 9),
  list(
    filter_checkbox("Geography", "Geography", full_Data, ~Geography),
    filter_select("EoI", "EoI Number", full_Data, ~EoI)
  ),
  reactable(full_Data,
            minRows = 2,
            highlight = TRUE,
            striped = TRUE)

)
```
